version: "3.9"
services:
  redis:
    image: "redis"
  elasticmq:
    image: "softwaremill/elasticmq-native"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
  gateway:
    build: .
    depends_on:
      - "redis"
      - "elasticmq"
    ports:
      - "4000:4000"
    links:
      - "redis:redis"
      - "elasticmq:sqs"
    command: ["npm", "run", "gateway:start"]
  processor:
    build: .
    depends_on:
      - "redis"
      - "elasticmq"
    links:
      - "redis:redis"
      - "elasticmq:sqs"
    command: ["npm", "run", "processor:start"]
    deploy:
      mode: replicated
      replicas: 2
  demoapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "processor"
      - "gateway"
    command: ["npm", "run", "demo:start"]
